[package]
name = "intcode"
version = "0.2.0"
authors = ["Drewtato <ai@andrewirino.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defaultmap = "^0.4.0"